server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html index.htm;

  # Manejar rutas de la Single Page Application (SPA)
  location / {
    try_files $uri $uri/ /index.html;
  }

  # No cachear favicons
  location ~* /favicon\.(ico|png)$ {
    expires -1;
    add_header Cache-Control "no-cache, must-revalidate";
  }

  # Cache para archivos estáticos
  location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|css|js)$ {
    expires 1M;
    access_log off;
    add_header Cache-Control "public";
  }
}
