services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: adorh/cotizaciones-backend:latest
    ports:
      - "8001:8000"
    volumes:
      - ./backend/cotizaciones.db:/app/cotizaciones.db
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: adorh/cotizaciones-frontend:latest
    ports:
      - "5003:80"
    restart: unless-stopped
    depends_on:
      - backend
